#!/usr/bin/env python
import sys

from barcodebattler.bb2.builder import BarcodeBattler2Builder

if __name__ == '__main__':
    while (True):
        barcode = input('Enter barcode (type exit to finish): ')
        if barcode == 'exit':
            sys.exit(0)

        barcode_data = BarcodeBattler2Builder().build(barcode)
        print(barcode_data.tabular_print())
